### PR TITLE
Solve issue on node_colors

### PR DESCRIPTION
**Pull request by davide-f**
I investigated the issue stated in #7 and this pull request solves the issue.
Changes can be performed in the case different pallettes shall be preferred.

### CODE REVIEW

**Comment by davide-f** [comment]
The tests fails because the difference changes the color mapping used to set the previous images, therefore most tests fail

**Comment by daschw** [comment]
Hi thanks a lot for reporting the issue and providing a PR. However, I don't think we want to fix the number of colors of the palette. In general this will provide colors "in between" the colors set by the color palette. I think I have a different fix for this, however, I'm not completely there yet ...

**Comment by davide-f** [comment]
Yeah, that's the drawback of my proposal; another (maybe) simple trick may be to consider the vector as a circular vector. A mod function may solve the issue

**Comment by davide-f** [comment]
I close this pull request and open it on a branch

**Pull request closed without merging**
